[package]
name = "tube-ingestor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neo4rs = "0.5.9"
tokio = "1.17.0"
csv = "1.1"
serde = { version = "1", features = ["derive"] }